version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./api_wallet/
    env_file: .env
    volumes:
      - static:/app/collected_static
    depends_on:
      - db
  nginx:
    build: ./nginx/
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/static
    depends_on:
      - backend
